name: Deploy WordPress to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.160.56 'mkdir -p /var/www/html/wordpress'
          scp -o StrictHostKeyChecking=no -r ./wordpress/* ubuntu@16.171.160.56:/var/www/html/wordpress/

      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.160.56 'sudo systemctl restart nginx'
